server:
  port: 8080
spring:
  application:
    name: gps-santander-impl
  config:
    import: application-dev.yml, application-prod.yml
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

