spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/gps_santander_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 123456
